server_url: "http://localhost:8000"
scheduler_api_key: "otk_98b8db24ccd64c92e1fdd9a232e209fa" # Your API key for scheduler authentication

# GPU allocation
num_gpus: 4 # Number of GPUs to request from scheduler (default: 4)

data_path: null
val_data_path: null
tokenizer_path: null
batch_size: 64
val_batch_size: 100
# Training duration - set ONE of these (num_steps takes precedence if both set)
num_epochs: 10 # Number of epochs (null = use num_steps)
num_steps: null # Total training steps (null = use num_epochs)
num_workers: 0

# reward function
## api reward function
reward:
  type: "remote"
  remote:
    reward_ip: "localhost"
    reward_port: null
    remote_api_key: null
    auto_start: true # Enable auto-start of reward server
  code:
    code_function: null
## code reward function

project_name: "agent_loop_training"
experiment_name: "math_with_tools"
save_freq: 100
test_freq: 50

temperature: 1
top_p: 1
max_new_tokens: 4096
max_prompt_tokens: 4096

algorithm: "toolcall"

logger_backends: ["console"] # options: ["console", "wandb"]
wandb_key: null
